version: '3.8'

volumes: 
  redis_dev: {}
  # 개발을 위해 로컬의 소스 폴더와 볼륨 연결시 각 서비스의 node_modules 폴더를 따로 저장해둘 도커 볼륨
  node_modules_admin-lobby-server:
  node_modules_customer-lobby-server:
  node_modules_admin-lobby-ui:
  node_modules_customer-lobby-ui:

services:
  redis:
    container_name: redis
    image: redis:5-alpine
    command: redis-server --requirepass votmdnjem
    ports:
      - 6379:6379
    volumes: 
      - redis_dev:/data
  admin-lobby-server:
    container_name: admin-lobby-server-dev # 실행될 컨테이터 인스턴스 이름
    build:
      context: ./projects # 빌드의 기준이 될 폴더
      dockerfile: ./admin-server.Dockerfile # 빌드에 사용될 도커 파일
      target: dev # 빌드에 사용될 도커 파일의 스테이지
    image: admin-lobby-server-dev:0.5 # 빌드될 이미지의 이름
    ports:
      - 3000:3000 # 호스트 컴퓨터와 포트와 컨테이너의 포드 연결
    volumes: 
      - /usr/src/chat-service/projects/admin-lobby-server/:/usr/src/app/ # 로컬의 소스를 컨테이너에 연결
      - node_modules_admin-lobby-server:/usr/src/app/node_modules # 컨테이너의 node_modules 폴더를 도커 볼륨에 연결
    command: npm run dev # nodemon 으로 소스 변경 감지
  customer-lobby-server:
    container_name: customer-lobby-server-dev
    build:
      context: ./projects
      dockerfile: ./customer-server.Dockerfile
      target: dev
    image: customer-lobby-server-dev:0.5
    ports:
      - 3001:3001
    volumes: 
      - /usr/src/chat-service/projects/customer-lobby-server/:/usr/src/app/
      - node_modules_customer-lobby-server:/usr/src/app/node_modules
    command: npm run dev
  admin-lobby-ui:
    container_name: admin-lobby-ui-dev
    build:
      context: ./projects
      dockerfile: ./admin-ui.Dockerfile
      target: dev
    image: admin-lobby-ui-dev:0.1
    ports:
      - 4200:4200
    volumes: 
      - /usr/src/chat-service/projects/admin-lobby-ui/:/usr/src/app/
      - node_modules_admin-lobby-ui:/usr/src/app/node_modules
    command: npm start # ng serve 로 소스 변경 감지
  customer-lobby-ui:
    container_name: customer-lobby-ui-dev
    build:
      context: ./projects
      dockerfile: ./customer-ui.Dockerfile
      target: dev
    image: customer-lobby-ui-dev:0.1
    ports:
      - 4201:4201
    volumes: 
      - /usr/src/chat-service/projects/customer-lobby-ui/:/usr/src/app/
      - node_modules_customer-lobby-ui:/usr/src/app/node_modules
    command: npm start
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      #KAFKA_CREATE_TOPICS: "sample:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181