version: '3.8'

volumes: 
  redis_dev: {}
  node_modules_admin-lobby-server:
  node_modules_customer-lobby-server:

services:
  redis:
    container_name: redis
    image: redis:5-alpine
    command: redis-server --requirepass votmdnjem
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - redis_dev:/data
  admin-lobby-server:
    container_name: admin-lobby-server
    build:
      context: ./projects
      dockerfile: ./admin-server.Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes: 
      - /usr/src/chat-service/projects/admin-lobby-server/:/usr/src/app/
      - node_modules_admin-lobby-server:/usr/src/app/node_modules
    command: npm run dev
  customer-lobby-server:
    container_name: customer-lobby-server
    build:
      context: ./projects
      dockerfile: ./customer-server.Dockerfile
      target: dev
    ports:
      - 3001:3001
    volumes: 
      - /usr/src/chat-service/projects/customer-lobby-server/:/usr/src/app/
      - node_modules_customer-lobby-server:/usr/src/app/node_modules
    command: npm run dev
  admin-lobby-ui:
    container_name: admin-lobby-ui
    build:
      context: ./projects
      dockerfile: ./admin-ui.Dockerfile
    ports:
      - 4200:4200
  customer-lobby-ui:
    container_name: customer-lobby-ui
    build:
      context: ./projects
      dockerfile: ./customer-ui.Dockerfile
    ports:
      - 4201:4201
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      #KAFKA_CREATE_TOPICS: "sample:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181