apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: admin-lobby-server
      name: admin-lobby-server
    spec:
      ports:
        - name: "3000"
          port: 3000
          targetPort: 3000
          nodePort: 30000
      selector:
        io.kompose.service: admin-lobby-server
      type: NodePort
    status:
      loadBalancer: {}
  # - apiVersion: v1
  #   kind: Service
  #   metadata:
  #     annotations:
  #       kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
  #       kompose.version: 1.22.0 (955b78124)
  #     creationTimestamp: null
  #     labels:
  #       io.kompose.service: admin-lobby-ui
  #     name: admin-lobby-ui
  #   spec:
  #     ports:
  #       - name: "4200"
  #         port: 4200
  #         targetPort: 4200
  #         nodePort: 31000
  #     selector:
  #       io.kompose.service: admin-lobby-ui
  #     type: NodePort
  #   status:
  #     loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: customer-lobby-server
      name: customer-lobby-server
    spec:
      ports:
        - name: "3001"
          port: 3001
          targetPort: 3001
          nodePort: 30001
      selector:
        io.kompose.service: customer-lobby-server
      type: NodePort
    status:
      loadBalancer: {}
  # - apiVersion: v1
  #   kind: Service
  #   metadata:
  #     annotations:
  #       kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
  #       kompose.version: 1.22.0 (955b78124)
  #     creationTimestamp: null
  #     labels:
  #       io.kompose.service: customer-lobby-ui
  #     name: customer-lobby-ui
  #   spec:
  #     ports:
  #       - name: "4201"
  #         port: 4201
  #         targetPort: 4201
  #         nodePort: 31001
  #     selector:
  #       io.kompose.service: customer-lobby-ui
  #     type: NodePort
  #   status:
  #     loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka
      name: kafka
    spec:
      ports:
        - name: "9092"
          port: 9092
          targetPort: 9092
      selector:
        io.kompose.service: kafka
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
      name: redis
    spec:
      ports:
        - name: "6379"
          port: 6379
          targetPort: 6379
      selector:
        io.kompose.service: redis
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: zookeeper
      name: zookeeper
    spec:
      ports:
        - name: "2181"
          port: 2181
          targetPort: 2181
      selector:
        io.kompose.service: zookeeper
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: admin-lobby-server
      name: admin-lobby-server
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: admin-lobby-server
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: admin-lobby-server
        spec:
          containers:
            - args:
                - npm
                - start
              image: admin-lobby-server:0.13
              name: admin-lobby-server
              imagePullPolicy: Never
              ports:
                - containerPort: 3000
              resources: {}
          restartPolicy: Always
    status: {}
  # - apiVersion: apps/v1
  #   kind: Deployment
  #   metadata:
  #     annotations:
  #       kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
  #       kompose.version: 1.22.0 (955b78124)
  #     creationTimestamp: null
  #     labels:
  #       io.kompose.service: admin-lobby-ui
  #     name: admin-lobby-ui
  #   spec:
  #     replicas: 1
  #     selector:
  #       matchLabels:
  #         io.kompose.service: admin-lobby-ui
  #     strategy: {}
  #     template:
  #       metadata:
  #         annotations:
  #           kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
  #           kompose.version: 1.22.0 (955b78124)
  #         creationTimestamp: null
  #         labels:
  #           io.kompose.service: admin-lobby-ui
  #       spec:
  #         containers:
  #           - args:
  #               - npm
  #               - start
  #             image: admin-lobby-ui:0.4
  #             name: admin-lobby-ui
  #             imagePullPolicy: Never
  #             ports:
  #               - containerPort: 4200
  #             resources: {}
  #         restartPolicy: Always
  #   status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: customer-lobby-server
      name: customer-lobby-server
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: customer-lobby-server
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: customer-lobby-server
        spec:
          containers:
            - args:
                - npm
                - start
              image: customer-lobby-server:0.13
              name: customer-lobby-server
              imagePullPolicy: Never
              ports:
                - containerPort: 3001
              resources: {}
          restartPolicy: Always
    status: {}
  # - apiVersion: apps/v1
  #   kind: Deployment
  #   metadata:
  #     annotations:
  #       kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
  #       kompose.version: 1.22.0 (955b78124)
  #     creationTimestamp: null
  #     labels:
  #       io.kompose.service: customer-lobby-ui
  #     name: customer-lobby-ui
  #   spec:
  #     replicas: 1
  #     selector:
  #       matchLabels:
  #         io.kompose.service: customer-lobby-ui
  #     strategy: {}
  #     template:
  #       metadata:
  #         annotations:
  #           kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
  #           kompose.version: 1.22.0 (955b78124)
  #         creationTimestamp: null
  #         labels:
  #           io.kompose.service: customer-lobby-ui
  #       spec:
  #         containers:
  #           - args:
  #               - npm
  #               - start
  #             image: customer-lobby-ui:0.4
  #             name: customer-lobby-ui
  #             imagePullPolicy: Never
  #             ports:
  #               - containerPort: 4201
  #             resources: {}
  #         restartPolicy: Always
  #   status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka
      name: kafka
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: kafka
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: kafka
        spec:
          containers:
            - env:
                - name: KAFKA_ADVERTISED_HOST_NAME
                  value: kafka
                - name: KAFKA_ZOOKEEPER_CONNECT
                  value: zookeeper:2181
                - name: KAFKA_PORT
                  value: "9092"
              image: wurstmeister/kafka:latest
              name: kafka
              ports:
                - containerPort: 9092
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
      name: redis
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: redis
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: redis
        spec:
          containers:
            - args:
                - redis-server
                - --requirepass
                - votmdnjem
              image: redis:5-alpine
              name: redis
              ports:
                - containerPort: 6379
              resources: {}
              volumeMounts:
                - mountPath: /data
                  name: redis-dev
          restartPolicy: Always
          volumes:
            - name: redis-dev
              persistentVolumeClaim:
                claimName: redis-dev
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-dev
      name: redis-dev
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: zookeeper
      name: zookeeper
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: zookeeper
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose-build.yml -o ./k8s
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: zookeeper
        spec:
          containers:
            - image: wurstmeister/zookeeper:latest
              name: zookeeper
              ports:
                - containerPort: 2181
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

