apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password 

#https://docs.dapr.io/operations/components/component-secrets/
#k8s secret: kubectl create secret generic redis --from-literal=redis-password=votmdnjem
#적용 kubectl apply -f ./components